sim/user/routes.py
from re import S

from flask_wtf import form
from sim.admin.routes import dtumum_filter, struktur
from flask import Flask, render_template, redirect, url_for, Blueprint, flash, request
from sim import app,db,bcrypt
from sim.models import Tdata_kegiatan, Tdataumumfilter, Tprofil, Tdataumum, Tdatasekolah, Takresklh, Tkecamatan, Tpengaduan, Tadmin, Tberita, Tinformasi, Tstruktur, Tartikel
from sim.user.forms import pengaduan_F,editpengaduan_F
import os
import secrets
from sim import app
from PIL import Image

guser= Blueprint('guser',__name__)

@guser.route("/about")
def profill():
    dt_profil=Tprofil.query.all()
    return render_template("t_user2/profil.html", dt_profil=dt_profil)

@guser.route("/", methods=['GET', 'POST'], defaults={"page": 1})
@guser.route("//<int:page>", methods=['GET', 'POST'])
def home(page):
    page = page
    pages = 3
    dt_struktur=Tstruktur.query.all()
    datastruktur= Tstruktur.query.paginate(page=page, per_page=4)
    dt_program=Tdata_kegiatan.query.all()
    dataprogram= Tdata_kegiatan.query.order_by(Tdata_kegiatan.id.desc()).paginate(page, pages, error_out=False)
    dt_umum=Tdataumum.query.all()
    dt_informasi=Tinformasi.query.all()
    datainformasi= Tinformasi.query.order_by(Tinformasi.id.desc()).paginate(page, pages, error_out=False)
    dt_berita=Tberita.query.all()
    dt_artikel=Tartikel.query.all()
    dataartikel= Tartikel.query.order_by(Tartikel.id.desc()).paginate(page=page, per_page=2)
    databerita= Tberita.query.order_by(Tberita.id.desc()).paginate(page, pages, error_out=False)
    dtfilter=Tdataumumfilter.query.all()
    for filter in dtfilter:
        s = filter
    dtumum_now = Tdataumum.query.filter_by(tahun=str(s.tahun)).all()
    return render_template("t_user2/landing.html", dt_program=dt_program, dt_umum=dt_umum, dt_informasi=dt_informasi, dtumum_now=dtumum_now, dt_berita=dt_berita, databerita=databerita, dataprogram=dataprogram, datainformasi=datainformasi,dt_struktur=dt_struktur,datastruktur=datastruktur,dt_artikel=dt_artikel,dataartikel=dataartikel)

@guser.route("/base", methods=['GET', 'POST'])
def base():
    form=pengaduan_F()
    data=Tpengaduan.query.all()
    if form.validate_on_submit():
        add= Tpengaduan(email=form.email.data,kategori=form.kategori.data,detail_pengaduan=form.detail_pengaduan.data)
        flash('Pengaduan anda berhasil di input, tunggu 2x24 jam untuk membuat pengaduan kembali dengan email yang sama','secondary')
        db.session.add(add)
        db.session.commit()
        return redirect(url_for('guser.home'))
    return render_template("t_user2/base.html", datapengaduan=data, form=form)


@guser.route("/detail-kegiatan", methods=['GET', 'POST'], defaults={"page": 1})
@guser.route("/detail-kegiatan/<int:page>", methods=['GET', 'POST'])
def datakegiatan(page):
    page = page
    pages = 7
    data=Tdata_kegiatan.query.all()
    datakegiatan = Tdata_kegiatan.query.order_by(Tdata_kegiatan.id.desc()).paginate(page, pages, error_out=False)
    if request.method == 'POST' and 'tag' in request.form:
        tag = request.form["tag"]
        search ="%{}%".format(tag)
        datakegiatan = Tdata_kegiatan.query.filter(Tdata_kegiatan.judul.like(search)).paginate(page, pages, error_out=False)
        return render_template("t_user2/program-kerja.html", datakegiatan=datakegiatan, tag=tag)
    return render_template("t_user2/program-kerja.html", datakegiatann=data, datakegiatan=datakegiatan)

@guser.route("/informasi", methods=['GET', 'POST'], defaults={"page": 1})
@guser.route("/informasi/<int:page>", methods=['GET', 'POST'])
def datainformasi(page):
    page = page
    pages = 5
    data=Tinformasi.query.all()
    datainformasi = Tinformasi.query.order_by(Tinformasi.id.desc()).paginate(page, pages, error_out=False)
    if request.method == 'POST' and 'tag' in request.form:
        tag = request.form["tag"]
        search ="%{}%".format(tag)
        datainformasi = Tinformasi.query.filter(Tinformasi.judul.like(search)).paginate(page, pages, error_out=False)
        return render_template("t_user2/informasi.html", datainformasi=datainformasi, tag=tag)
    return render_template("t_user2/informasi.html", informasiii=data, datainformasi=datainformasi)


@guser.route("/detail-informasi/<int:ed_id>/detail", methods=['GET', 'POST'])
def informasi_detail(ed_id):
    datainformasi=Tinformasi.query.get_or_404(ed_id)
    return render_template("t_user2/informasi-detail.html", datainformasi=datainformasi)


@guser.route("/dashboard-user")
def dasboard():
    return render_template("t_user/index.html")

@guser.route("/struktur-orgnssi", methods=['GET', 'POST'], defaults={"page": 1})
@guser.route("/struktur-orgnssi/<int:page>", methods=['GET', 'POST'])
def datastruktur(page):
     page = page
     pages = 10
     dataa=Tstruktur.query.all()
     datastruktur = Tstruktur.query.paginate(page, pages, error_out=False)
     if request.method == 'POST' and 'tag' in request.form:
        tag = request.form["tag"]
        search ="%{}%".format(tag)
        datastruktur = Tstruktur.query.filter(Tstruktur.judul.like(search)).paginate(page, pages, error_out=False)
        return render_template("t_user2/strukturorganisasi.html", datastruktur=datastruktur, tag=tag)
     return render_template("t_user2/strukturorganisasi.html", struktur=dataa, datastruktur=datastruktur)

@guser.route("/datasekolahh", methods=['GET', 'POST'], defaults={"page": 1})
@guser.route("/datasekolahh/<int:page>", methods=['GET', 'POST'])
def datasekolah(page):
    page = page
    pages = 10
    data=Tdatasekolah.query.all()
    datasekolah = Tdatasekolah.query.order_by(Tdatasekolah.id.desc()).paginate(page, pages, error_out=False)
    if request.method == 'POST' and 'tag' in request.form:
        tag = request.form["tag"]
        search ="%{}%".format(tag)
        datasekolah = Tdatasekolah.query.filter(Tdatasekolah.npsn.like(search)).paginate(page, pages, error_out=False)
        return render_template("t_user2/datasekolah.html", datasekolah=datasekolah, tag=tag)
    return render_template("t_user2/datasekolah.html", sekolah=data, datasekolah=datasekolah)

@guser.route("/dataumum", methods=['GET', 'POST'], defaults={"page": 1})
@guser.route("/dataumum/<int:page>", methods=['GET', 'POST'])
def dataumum(page):
    page = page
    pages = 10
    data=Tdataumum.query.all()
    dataumum = Tdataumum.query.order_by(Tdataumum.id.desc()).paginate(page, pages, error_out=False)
    if request.method == 'POST' and 'tag' in request.form:
        tag = request.form["tag"]
        search ="%{}%".format(tag)
        dataumum = Tdataumum.query.filter(Tdataumum.tahun.like(search)).paginate(page, pages, error_out=False)
        return render_template("t_user2/dataumum.html", dataumum=dataumum, tag=tag)
    return render_template("t_user2/dataumum.html", dt_umum=data, dataumum=dataumum)

@guser.route("/detail-datasekolah/<int:ed_id>/detail", methods=['GET', 'POST'])
def datasekolah_detail(ed_id):
    datasekolah=Tdatasekolah.query.get_or_404(ed_id)
    return render_template("t_user2/detail-sekolah.html", datasekolah=datasekolah)


@guser.route("/beritaa", methods=['GET', 'POST'], defaults={"page": 1})
@guser.route("/beritaa/<int:page>", methods=['GET', 'POST'])
def berita(page):
    page = page
    pages = 3
    dt_berita=Tberita.query.all()
    berita = Tberita.query.order_by(Tberita.id.desc()).paginate(page, pages, error_out=False)
    if request.method == 'POST' and 'tag' in request.form:
        tag = request.form["tag"]
        search ="%{}%".format(tag)
        berita = Tberita.query.filter(Tberita.judul.like(search)).paginate(page, pages, error_out=False)
        return render_template("t_user2/berita.html", berita=berita, tag=tag)
    return render_template("t_user2/berita.html", dt_berita=dt_berita, berita=berita)

@guser.route("/detail-berita/<int:ed_id>/detail", methods=['GET', 'POST'])
def berita_detail(ed_id):
    beritaa=Tberita.query.get_or_404(ed_id)
    return render_template("t_user2/beritaid.html", data=beritaa)


@guser.route("/artikel", methods=['GET', 'POST'], defaults={"page": 1})
@guser.route("/artikel/<int:page>", methods=['GET', 'POST'])
def dataartikell(page):
    page = page
    pages = 5
    data=Tartikel.query.all()
    dataartikel = Tartikel.query.order_by(Tartikel.id.desc()).paginate(page, pages, error_out=False)
    if request.method == 'POST' and 'tag' in request.form:
        tag = request.form["tag"]
        search ="%{}%".format(tag)
        dataartikel = Tartikel.query.filter(Tartikel.judul.like(search)).paginate(page, pages, error_out=False)
        return render_template("t_user2/artikel.html", dataartikel=dataartikel, tag=tag)
    return render_template("t_user2/artikel.html", artikel=data, dataartikel=dataartikel)


@guser.route("/detail-artikel/<int:ed_id>/detail", methods=['GET', 'POST'])
def artikel_detail(ed_id):
    artikel=Tartikel.query.get_or_404(ed_id)
    return render_template("t_user2/artikelid.html", data=artikel)

sim/templates/t_user2/artikel.html
{% extends "t_user2/base.html" %}

{% block konten%}
<section id="works">

    <div class="container">
        
        <!-- section title -->
        <h2 class="section-title wow fadeInUp">Data artikel</h2>

        <div class="spacer" data-height="60"></div>

        <div class="container">
                
            
            <div class="row">
                <form action="" method="POST" class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search pb-4">
                    <div class="input-group">
                      <input type="text" class="form-control bg-light border-0 small" placeholder="ketik NPSN ..."
                          aria-label="Cari" aria-describedby="basic-addon2" name="tag" id="tag">
                      <div class="input-group-append">
                        <input class="btn btn-primary" type="submit" value="Cari">
                      </div>
                    </div>
                  </form>
                  <strong style="padding-left: 20px;">Cari Untuk : {{ tag }}</strong>
            </div>



                <div class="col-md-12 triangle-left-md triangle-top-sm">
                    <div class="rounded bg-white shadow-dark padding-30">
                        <div class="row">
                            <div class="col-md-12">
                                <!-- about text -->
                               
                             
                                <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="2">
                                    <thead>
                                        <tr align="center" style="background-color: rgb(252, 159, 98);">
                                            <th >Tanggal Post</th>
                                            <th >Judul</th>
                                            <th >Link</th>
                                            <th>detail</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                    </tfoot>
                                    <tbody>
                                        {% for data in dataartikel.items %}
                                        <tr>
                                            <td>{{data.tgl_post}}</td>
                                            <td>{{data.judul}}</td>
                                            <td>{{data.link}}</td>
                                            <td><a class="btn btn-sm btn-danger" href="{{url_for('guser.artikel_detail', ed_id=data.id)}}">Detail</a></td>
                                           
                                            
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                    </table>
                                    <nav aria-label="Page navigation example">
                                        <ul class="pagination">
                                          {% if dataartikel.has_prev %}
                                            <li class="page-item"><a class="page-link" href="{{ url_for('guser.dataartikell', page=dataartikel.prev_num)}}">Previous</a></li>
                                          {% else %}
                                            <li class="page-item disabled"><a class="page-link">Previous</a>
                                          {% endif %}
                                            </li>
                        
                                          {% for page in dataartikel.iter_pages(left_edge=3, right_edge=3) %}
                                          {% if page %}
                                              {% if page==dataartikel.page %}
                                              <li class="page-item active"><a class="page-link" href="{{ url_for('guser.dataartikell', page=page)}}">{{ page }}</a></li>
                                              {% else %}
                                              <li class="page-item"><a class="page-link" href="{{ url_for('guser.dataartikell', page=page)}}">{{ page }}</a></li>
                                              {% endif %}
                                          {% else %}
                                             <li class="page-item disabled" id="example_ellipsis"><a class="page-link" href="#">...</a></li>
                                          {% endif %}
                                          {% endfor %}
                        
                                          {% if dataartikel.has_next %}
                                          <li class="page-item"><a class="page-link" href="{{ url_for('guser.dataartikell', page=dataartikel.next_num)}}">Next</a></li>
                                          {% else %}
                                          <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                                          {% endif %}
                                        </ul>
                                      </nav>
                      
                                <div class="spacer d-md-none d-lg-none" data-height="30"></div>
                            </div>
                           
                        </div>
                    </div>
                </div>
               
            </div>
            <!-- row end -->

            <div class="spacer" data-height="70"></div>
        
        </div>
  

    </div>

</section>
{% endblock%}

sim/templates/t_user2/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>PAUD - Kota Tidore</title>
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="Free Website Template" name="keywords">
        <meta content="Free Website Template" name="description">

        <!-- Favicon -->
        <link href="{{ url_for ('static', filename="tuser2/img/logo_tidore.png")}}" rel="icon">
        <link rel="stylesheet" href="{{ url_for ('static', filename="tuser/css/bootstrap.min.css")}}" type="text/css" media="all">
        <!-- Google Font -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap" rel="stylesheet">

        <!-- CSS Libraries -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for ('static', filename="tuser2/lib/animate/animate.min.css")}}" type="text/css" media="all">
        <link rel="stylesheet" href="{{ url_for ('static', filename="tuser2/lib/owlcarousel/assets/owl.carousel.min.css")}}" type="text/css" media="all">
        <link rel="stylesheet" href="{{ url_for ('static', filename="tuser2/lib/lightbox/css/lightbox.min.css")}}" type="text/css" media="all">

        <!-- Template Stylesheet -->
        
        
        <link rel="stylesheet" href="{{ url_for ('static', filename="tuser2/css/style.css")}}" type="text/css" media="all">
    </head>

    <body data-spy="scroll" data-target=".navbar" data-offset="51">
        <!-- Nav Bar Start -->
        <div class="navbar navbar-expand-lg bg-light navbar-light">
            <div class="container-fluid">
                <a href="index.html" class="navbar-brand"><img src="{{ url_for ('static', filename="tuser2/img/paud2.png")}}" alt="logo Paud" width="60px">PAUD-Kota Tidore</a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav ml-auto">
                        <a href="{{url_for('guser.home')}}" class="nav-item nav-link active">Home</a>
                        <a href="{{url_for('guser.profill')}}" class="nav-item nav-link" >About</a>
                        <a href="{{url_for('guser.datainformasi')}}" class="nav-item nav-link">Informasi</a>
                        <a href="{{url_for('guser.berita')}}" class="nav-item nav-link">Berita</a>
                        <a href="{{url_for('guser.datakegiatan')}}" class="nav-item nav-link">Program Kerja</a>
                        <a href="{{url_for('guser.datastruktur')}}" class="nav-item nav-link">Struktur Organisasi</a>
                        <a href="{{url_for('guser.dataartikell')}}" class="nav-item nav-link">Artikel</a>
                        <a href="{{url_for('guser.base')}}" class="nav-item nav-link">Pengaduan</a>
                    </div>
                </div>
                
            </div>
        </div>
        <!-- Nav Bar End -->


        <!-- Hero Start -->
        <div class="hero" id="home">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-sm-12 col-md-6">
                        
                        <div class="hero-content">
                               
                            <div class="hero-text">   
                                <p>Bidang PAUD</p>
                                <h1 class="">Dinas Pendidikan Kota Tidore</h1>
                                <h2></h2>
                                <div class="typed-text">Selamat Datang ! , Sistem Informasi PAUD-Tikep, Pendidikan Anak Usia Dini, |PAUD-Sehat-Cerdas-Ceria, </div>
                            </div>
                            <div class="hero-btn">
                                <a class="btn" href="{{url_for('guser.datasekolah')}}">Data Sekolah</a>
                                <a class="btn" href="{{url_for('guser.base')}}">Pengaduan</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-6 d-none d-md-block">
                        <div class="hero-image">
                            <img src="{{ url_for ('static', filename="tuser2/img/logo_tidore.png")}}" alt="Hero Image">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Hero End -->


        {% with messages= get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, massage in messages %}

                <div class="alert alert-{{category}}">
                        {{massage}}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}

                {% block dasboard%}
                {% endblock %}

                {% block footer%}
                {% endblock %}

                {% block konten%}
                <div class="contact wow fadeInUp" data-wow-delay="0.1s" id="contact">
                    <div class="container-fluid">
                        <div class="container">
                            <div class="row align-items-center">
                                <div class="col-md-4">
                                </div>
                                <div class="col-md-8">
                                    <div class="contact-form">
                                        <div id="success"></div>
                                        <form method="POST" enctype="multipart/form-data" style="color: aliceblue;" >
                                                    {{form.hidden_tag()}}
                                                <div class="form-group">
        
                                                    {{form.email.label(class="form-control-label")}}
                                                    {% if form.email.errors %}
                                                         {{form.email(class="form-control is-invalid")}}
                                                
                                                         <div class="invalid-feedback">
                                                             {%for error in form.email.errors %}
                                                             <span>{{error}}</span>
                                                             {% endfor %}
                                                         </div>
                                                    {%else%}
                                                        {{form.email(class="form-control")}}
                                                    
                                                    {%endif%}
                                                </div>
                                                  <div class="form-group">
                                                {{form.kategori.label(class="form-control-label")}}
                                                {% if form.kategori.errors %}
                                                     {{form.kategori(class="form-control is-invalid")}}
                                            
                                                     <div class="invalid-feedback">
                                                         {%for error in form.kategori.errors %}
                                                         <span>{{error}}</span>
                                                         {% endfor %}
                                                     </div>
                                                {%else%}
                                                    {{form.kategori(class="form-control")}}
                                                
                                                {%endif%}
                                            </div>
                                            <div class="form-group"> 
                                                {{form.detail_pengaduan.label(class="form-control-label")}}
                                                {% if form.detail_pengaduan.errors %}
                                                    {{form.detail_pengaduan(class="form-control is-invalid")}}
                                        
                                                <div class="invalid-feedback">
                                                    {% for error in form.detail_pengaduan.errors %}
                                                    <span>{{error}}</span>
                                                    {% endfor %}
                                                </div>
                                                {% else %}
                                                    {{form.detail_pengaduan(class="form-control")}}
                                                {% endif %}
                                            </div>
                                            <div class="form-group" style="color: red;">
                                                {{form.submit(class="btn btn-primary")}}
                                            </div>
                                        
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endblock %}

            </div>
        <!-- Footer Start -->
        <div class="footer wow fadeIn" data-wow-delay="0.3s">
            <div class="container-fluid">
                <div class="container">
                    <div class="footer-info">
                        <h1>-SISTEM INFORMASI-</h1>
                        <h2>PENDIDIKAN ANAK USIA DINI</h2>
                        <h3>KOTA TIDORE KEPULAUAN</h3>
                        <div class="footer-menu">
                            <p>+628-219-009-1585</p>
                            <p>paudnitidore@gmail.com</p>
                        </div>
                        <div class="footer-social">
                            <a href=""><i class="fab fa-twitter"></i></a>
                            <a href=""><i class="fab fa-facebook-f"></i></a>
                            <a href=""><i class="fab fa-youtube"></i></a>
                            <a href=""><i class="fab fa-instagram"></i></a>
                            <a href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
                <div class="container copyright">
                    <p>&copy; <a href="#">Tim-timan</a>, All Right Reserved | Designed By <a href="https://htmlcodex.com">Informatic of UMMU</a></p>
                </div>
            </div>
        </div>
        
      
        <!-- Footer End -->
        
        
        <!-- Back to top button -->
        <a href="#" class="btn back-to-top"><i class="fa fa-chevron-up"></i></a>
        
        
        <!-- Pre Loader -->
        <div id="loader" class="show">
            <div class="loader"></div>
        </div>

        
        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <script src="{{ url_for ('static', filename="tuser2/lib/easing/easing.min.js")}}"></script>
        <script src="{{ url_for ('static', filename="tuser2/lib/wow/wow.min.js")}}"></script>
        <script src="{{ url_for ('static', filename="tuser2/lib/waypoints/waypoints.min.js")}}"></script>
        <script src="{{ url_for ('static', filename="tuser2/lib/typed/typed.min.js")}}"></script>
        <script src="{{ url_for ('static', filename="tuser2/lib/owlcarousel/owl.carousel.min.js")}}"></script>
        <script src="{{ url_for ('static', filename="tuser2/lib/isotope/isotope.pkgd.min.js")}}"></script>
        <script src="{{ url_for ('static', filename="tuser2/lib/lightbox/js/lightbox.min.js")}}"></script>
        
        
        
        <!-- Contact Javascript File -->
        <script src="mail/jqBootstrapValidation.min.js"></script>
        <script src="mail/contact.js"></script>

        <!-- Template Javascript -->
       
        <script src="{{ url_for ('static', filename="tuser2/js/main.js")}}"></script>
    </body>
</html>

sim/templates/t_user2/berita.html
{% extends "t_user2/base.html" %}

{% block konten%}
<div class="experience" id="experience">
    <div class="container">
        <header class="section-header text-center wow zoomIn" data-wow-delay="0.1s">
            <h2>Berita Terbaru</h2>
        </header>
        <form action="" method="POST" class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search pb-4">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Cari dengan Judul ..."
                  aria-label="Cari" aria-describedby="basic-addon2" name="tag" id="tag">
              <div class="input-group-append">
                <input class="btn btn-primary" type="submit" value="Cari">
              </div>
            </div>
          </form>
          <strong style="padding-left: 20px;">Cari Untuk : {{ tag }}</strong>
        {% for data in berita.items %}
        <div class="timeline">
            <div class="timeline-item left wow slideInRight" data-wow-delay="0.1s">
                <div class="timeline-text">
                    <div class="timeline-date">{{data.tgl_post}}</div>
                    <h2>{{data.judul}}</h2> <p><img src="{{url_for('static', filename='foto/' +data.foto)}}" alt="..." width="150px"></p>
                    <h4>{{data.berita}}</h4>
                    <button style="background-color: red;"><a href="{{url_for('guser.berita_detail', ed_id=data.id)}}">Detail</a></button>
                </div>
            </div>  
        </div>
        {% endfor %}
        <div class="timeline">
            <div class="timeline-item right wow slideInLeft" data-wow-delay="0.1s">
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                      {% if berita.has_prev %}
                        <li class="page-item"><a class="page-link" href="{{ url_for('guser.berita', page=berita.prev_num)}}">Previous</a></li>
                      {% else %}
                        <li class="page-item disabled"><a class="page-link">Previous</a>
                      {% endif %}
                        </li>
            
                      {% for page in berita.iter_pages(left_edge=3, right_edge=3) %}
                      {% if page %}
                          {% if page==berita.page %}
                          <li class="page-item active"><a class="page-link" href="{{ url_for('guser.berita', page=page)}}">{{ page }}</a></li>
                          {% else %}
                          <li class="page-item"><a class="page-link" href="{{ url_for('guser.berita', page=page)}}">{{ page }}</a></li>
                          {% endif %}
                      {% else %}
                         <li class="page-item disabled" id="example_ellipsis"><a class="page-link" href="#">...</a></li>
                      {% endif %}
                      {% endfor %}
            
                      {% if berita.has_next %}
                      <li class="page-item"><a class="page-link" href="{{ url_for('guser.berita', page=berita.next_num)}}">Next</a></li>
                      {% else %}
                      <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
                      {% endif %}
                    </ul>
                  </nav>
            </div>
        </div>
        
    </div>

   
</div>
{% endblock%}